import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def to_slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9-]+", "-", value.strip().lower()).strip("-")
    return re.sub(r"-{2,}", "-", slug)


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap a new skill skeleton.")
    parser.add_argument("name", help="Skill name (will be normalized to slug).")
    parser.add_argument("--description", required=True, help="Short trigger description.")
    parser.add_argument("--owners", default="platform-team", help="owners frontmatter field.")
    parser.add_argument("--maturity", default="experimental", choices=["experimental", "stable", "deprecated"])
    parser.add_argument("--review-date", default="2026-03-09", help="last_reviewed date YYYY-MM-DD.")
    args = parser.parse_args()

    name = to_slug(args.name)
    skill_dir = ROOT / name
    agents_dir = skill_dir / "agents"
    skill_md = skill_dir / "SKILL.md"
    openai_yaml = agents_dir / "openai.yaml"
    changelog = skill_dir / "CHANGELOG.md"

    skill_dir.mkdir(parents=True, exist_ok=True)
    agents_dir.mkdir(parents=True, exist_ok=True)

    if not skill_md.exists():
        skill_md.write_text(
            (
                f"---\n"
                f"name: {name}\n"
                f'description: "{args.description}"\n'
                f'version: "0.1.0"\n'
                f'owners: "{args.owners}"\n'
                f'last_reviewed: "{args.review_date}"\n'
                f'maturity: "{args.maturity}"\n'
                f"---\n\n"
                f"# {name}\n\n"
                "## Cuando usar\n\n"
                "- Completar segun caso.\n\n"
                "## Flujo\n\n"
                "1. Completar flujo.\n\n"
                "## Integracion\n\n"
                "- Completar integraciones.\n"
            ),
            encoding="utf-8",
        )

    if not openai_yaml.exists():
        openai_yaml.write_text(
            (
                "interface:\n"
                f'  display_name: "{name}"\n'
                '  short_description: "TODO"\n'
                f'  default_prompt: "Use ${name} to execute its specialized workflow."\n\n'
                "policy:\n"
                "  allow_implicit_invocation: true\n"
            ),
            encoding="utf-8",
        )

    if not changelog.exists():
        changelog.write_text(
            (
                "# Changelog\n\n"
                "## 0.1.0 - 2026-03-09\n"
                "- Initial skill scaffold generated by bootstrap script.\n"
            ),
            encoding="utf-8",
        )

    print(f"Bootstrapped skill: {skill_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
